version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: plant-recognition-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ""
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - plant-network

  # Redis Commander - Web UI for Redis (Optional)
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: plant-recognition-redis-ui
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - plant-network

volumes:
  redis_data:
    driver: local

networks:
  plant-network:
    driver: bridge
